### ISSUE TITLE
update compatibility with Jupyterlab-0.35.0rc1

### ISSUE THREAD

**Issue by stonebig** [pyviz/pyviz_comms#15]
you will  apparently need to do upgrade again https://github.com/pyviz/pyviz_comms/blob/master/package.json#L32..L35

to @0.19.0-alpha.0 at the moment

**Comment by philippjfr** [comment]
Thanks @stonebig, your efforts in keeping on top of these changes are hugely appreciated. I do wonder if there isn't a better way, pushing new and backward incompatible releases every time something in JLab changes doesn't seem like a great long term approach.

**Comment by stonebig** [comment]
I suppose there is no workaround to that practice till Jupyterlab-1.0.
