### ISSUE TITLE
Provide notebook extension baseclass

### ISSUE THREAD

**Issue by philippjfr** [pyviz/pyviz_comms#16]
pyviz_comms should provide a baseclass for notebook extensions which can be used by downstream packages. Having separate extensions in projects like holoviews and panel is already less than ideal however having a baseclass for these extensions here means that common components don't have to be duplicated across projects. Additionally, one major problem with the current organization is that while holoviews and panel extensions are mostly cross-compatible, when the holoviews extension is loaded and a plot is displayed with `panel` the holoviews extension will not know how to clean up panel Viewables.

**Comment by jlstevens** [comment]
Makes sense to me.
