### ISSUE TITLE
Please update npm @pyviz/jupyterlab_holoviews

### ISSUE THREAD

**Issue by athornton** [pyviz/pyviz_comms#19]
The npm package at https://www.npmjs.com/package/@pyviz/jupyterlab_holoviews is still at 0.5.2.  It would be nice to not have to build it locally.

**Comment by philippjfr** [comment]
jupyterlab_holoviews should no longer be used please use https://www.npmjs.com/package/@pyviz/jupyterlab_pyviz instead.
