### ISSUE TITLE
Compatibility with jupyterlab-1.0 alphas

### ISSUE THREAD

**Issue by stonebig** [pyviz/pyviz_comms#35]
https://github.com/pyviz/pyviz_comms/pull/34

**Comment by stonebig** [comment]
Still some Hope ?

**Comment by philippjfr** [comment]
Apologies never came back to this. Want to fix the CI before I tag.

**Comment by philippjfr** [comment]
Will try to do it this afternoon.

**Comment by philippjfr** [comment]
Okay, didn't get there over the weekend but I just pushed it now, you can get it with:

```
jupyter labextension install @pyviz/jupyterlab_pyviz@next
```

which is also mentioned in the README.
