### ISSUE TITLE
Compatible issues with JupyterLab 1.0.0

### ISSUE THREAD

**Issue by dclong** [pyviz/pyviz_comms#42]
I'm using JupyterLab 1.0.0 and installed pyviz_comms via the following command.
```
jupyter labextension install @pyviz/jupyterlab_pyviz@next
```
How I cannot launch a notebook and encounter the following error. There was no issue before installing pyviz_comms.
```
Launch Error
Cannot read property 'addFactory' of undefined
```

**Comment by philippjfr** [comment]
I'll try to push out an update today.

**Comment by philippjfr** [comment]
I've released a new version of the extension on npm.
