### ISSUE TITLE
compatibility of jupyterlab_pyviz with Jupyterlab-0.33.4 ? 

### ISSUE THREAD

**Issue by stonebig** [pyviz/pyviz_comms#7]
I currently get an error:
````
npm.CMD pack @pyviz/jupyterlab_pyviz
pyviz-jupyterlab_pyviz-0.5.3.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=3.0.3 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services
````

would it be possible to get a patch release to fix this ?

**Comment by philippjfr** [comment]
Upgrading the extension to work with latest JLab is very high on my to-do list.

**Comment by ddaahk** [comment]
+1 for this! Which version of lab is the current pyviz compatible with?

**Comment by ddaahk** [comment]
I'm particularly interested in @pyviz/jupyterlab_holoviews

**Comment by RafalSkolasinski** [comment]
I think with 0.32 everything works fine.

**Comment by ddaahk** [comment]
@RafalSkolasinski thanks!

**Comment by athornton** [comment]
With today's master, updating the version requirements is easy enough to do, but IComm is no longer asynchronous (and thus a Promise), but synchronous, and therefore I don't yet know what would need to change to make the CommProxy either work or be eliminated.

**Comment by philippjfr** [comment]
>IComm is no longer asynchronous (and thus a Promise), but synchronous

Didn't they just make it asynchronous in the last release? If that's the case we can simply try rolling back my previous change.

**Comment by philippjfr** [comment]
For further reference here's the PR that changed the comms again: https://github.com/jupyterlab/jupyterlab/pull/4697/files

**Comment by philippjfr** [comment]
I've just pushed changes to make the extension compatible and pushed the updated extension to npm. @stonebig Would you mind testing?

**Comment by stonebig** [comment]
great news ! I will try again this week-end
